### ISSUE TITLE
Add GitHub Actions to Dependabot config

### ISSUE THREAD

**Issue by PeterSufliarsky** [PeterSufliarsky/cowrie-rest#35]
```
- package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      # Check for updates to GitHub Actions every weekday
      interval: "daily"
```
