### ISSUE TITLE
Integrade code scanning with Snyk

### ISSUE THREAD

**Issue by PeterSufliarsky** [PeterSufliarsky/cowrie-rest#43]
```
name: Example workflow for Maven using Snyk
on: push
jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/maven@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
```
